datasource:
    pubdb:
        driverClassName: "com.mysql.jdbc.Driver"
        url: "jdbc:mysql://de-c-my-db.fttinc.kr:19336/simpleboard?autoReconnect=true&initialTimeout=3&maxReconnects=5&useUnicode=true&characterEncoding=utf8"
        username: "dev433"
        password: "433eoqkr)(!"
        
    localdb:
        driverClassName: "com.mysql.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/simpleboard?autoReconnect=true&initialTimeout=3&maxReconnects=5&useUnicode=true&characterEncoding=utf8"
        username: "lunker"
        password: "dongqlee"
   